### ISSUE TITLE
YAML yaml is allowed property names with underscores

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#10]
The JSON property names never have spaces. They have underscores instead.
However, some yaml property names have spaces and some have underscores.

For example:
ID: 029342ac-3023-43f2-8d13-444142f50383
RuleID: CG0136
`value_is_literal` in the yaml is being converted to `value is literal` in the yaml, but it should not be.

Spaces in property names should be converted to underscores when converting from yaml to json, but json should not be converted to yaml. Conversion should only happen in one direction.

**Comment by htu** [comment]
This has been fixed in v0.4.2
