### ISSUE TITLE
Comment is being deleted

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#12]
ID: 1d0dadd2-0591-4e89-8b9c-85c48fd0f060
RuleId: CG0659

Existing comments should be preserved

**Comment by htu** [comment]
I forgot turning on the comment process. CG0659 is showing comments now. Do you have more rules with comments? I'd like to test couple of more rules.

**Comment by gerrycampion** [comment]
27b19da0-4601-490e-bbfe-a0d389d1c46a
513d1590-579f-4909-be51-745a306657af
51868eb6-d402-4259-8734-807c0e56dddf

**Comment by htu** [comment]
I am closing this one since this is fixed after I turned on the comment processing.
