### ISSUE TITLE
Rules are being removed

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#4]
Some rules are being removed and they should not be.
For example:
id: 435371d7-9e2c-4953-aae1-ed43cbc62fa5
Rule id: CG0100

If there are duplicate rule ids, the citations should be applied to all copies of the rule and duplicate rule ids can be logged in the log file.

**Comment by htu** [comment]
I commented out the de-duplication code. So it should not try to remove duplicated rule anymore.

**Comment by htu** [comment]
This has been fixed in v0.4.1
