### ISSUE TITLE
Executability being overwritten

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#5]
Just like Issue #2, properties should never be overwritten.
It appears that Executability is being overwritten with `Partially Executable` in many cases.
Instead,
1. Executability should only be added if it doesn't already exist as a property on the rule.
2. Executability should be set to `Fully Executable` (if it doesn't already exist as a property on the rule).

**Comment by htu** [comment]
This has been fixed in v0.4.1
