### ISSUE TITLE
Citations for rules with multiple rule id's are being overwritten

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#9]
If any rules have multiple rule ids, the citations should be copied into the rule for both ruleids.

Example 1
ID: 54ce26c6-1c7e-4bbf-ba68-c4aea2326b56
RuleId's: CG0509, CG0630
After being processed, the reference for CG0630 is being removed.

Example 2
ID: 405bea03-36b3-4b74-affe-22a3f2984bf9
RuleId's: CG0234, CG0235
After being processed, the reference for CG0235 is being removed.

Example 3
ID: 6a0c4575-b736-4014-af26-0618a30047b4
RuleId's: CG0110, CG0111

Example 4
ID: bbe42844-04fa-4e99-87ba-7c8bdced0c6a
RuleId's: CG0507, CG0622

Example 5:
ID: f59bb78b-dab4-4600-a7bd-b26ecfca7691
RuleId's: CG0232, CG0233

**Comment by htu** [comment]
Question on this: Is this going to be general practice, i.e., multiple rule definition could become one rule file in rule engine? This could get the rule validation and engine become very complicated.

**Comment by gerrycampion** [comment]
Yes, this is general practice.
It will be more common when we add FDA rules that match existing CDISC rules, but it already exists within some CDISC rules.

It is unavoidable in some scenarios. For example, you can't implement CG0110 without implementing CG0111. Here is the acceptance criteria:
CG0110: `If DOSTXT ^= null -> --DOSE = null`
CG0111: `If DOSE ^= null -> --DOSTXT = null`

In the rule engine, both of these rules translate to the same failure criteria:
`--DOSTXT ^= null and --DOSE ^= null`

**Comment by htu** [comment]
Can you take a look at the current CG0110? it has this error: Incorrect type. Expected "array".yaml-schema: file:///CORE-base.json(0)
No quick fixes available.  

 Should I just ignore it and I need to deal with it now?

**Comment by gerrycampion** [comment]
You can ignore that because it is an issue in the original prod rule. I will fix this in prod.

**Comment by gerrycampion** [comment]
Now, it looks like the citations are only being pulled in for the first rule id. We should be adding citations for all matching rule id's within a rule.

**Comment by htu** [comment]
To resolve this, I need to get a list Rule ID included in a rule file. Then I will loop through them to check and add citations.

**Comment by htu** [comment]
Resolved.
